### ISSUE TITLE
作者可出个详细使用说明吗

### ISSUE THREAD

**Issue by banbanfan** [imsyy/DailyHotApi#25]
### 问题描述

作者可出个详细使用说明吗，折磨不透啊，api的+bilibili访问404，不是403

**Comment by banbanfan** [comment]
[root@root]# node -v
v16.18.1
[root@root]# npm -v
8.19.2

**Comment by dahaichaoyong** [comment]
#27

**Comment by James904141** [comment]
按照这个方法pnpm install 后没出现dist文件夹啊，大佬怎么办？
