### ISSUE TITLE
添加吾爱破解接口

### ISSUE THREAD

**Issue by love2wind** [imsyy/DailyHotApi#29]
### 希望添加哪个接口？

吾爱破解

### 官方接口地址

https://www.52pojie.cn/

### 其他信息

或者类似discuz论坛的API怎么写

**Comment by LjyLab** [comment]
可以抓标签属性获取标签的内容

**Comment by imsyy** [comment]
已支持

**Comment by love2wind** [comment]
> 已支持

好的，感谢
