### ISSUE TITLE
vercel.json不兼容最新规则，最新版本部署会报500错误

### ISSUE THREAD

**Issue by ilanks** [imsyy/DailyHotApi#35]
### 问题描述

{
  "version": 2,
  "functions": {
    "api/index.js": {
      "runtime": "@vercel/node@3.0.11"
    }
  },
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/"
    }
  ],
  "headers": [{
    "source": "/(.*)",
    "headers": [
      {
        "key": "Access-Control-Allow-Credentials",
        "value": "true"
      },
      {
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      },
      {
        "key": "Access-Control-Allow-Methods",
        "value": "GET,OPTIONS,PATCH,DELETE,POST,PUT"
      },
      {
        "key": "Access-Control-Allow-Headers",
        "value": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
      }
    ]
  }]
}  我改了一下，但还是不能正常运行，会报错

### 补充信息

无论怎么改，最新部署会报500错误

**Comment by imsyy** [comment]
已修复
