### ISSUE TITLE
QQ音乐的接口获取失败了

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [imsyy/DailyHotApi#45]
### 问题描述

接口数据获取失败
![image](https://github.com/imsyy/DailyHotApi/assets/66905526/eb099a89-9922-4f2c-98a4-70e638abdfe3)

**Comment by imsyy** [comment]
> [!TIP]
> ### 目前正基于 `Hono` 和 `typescript` 重构该项目，敬请期待

**Comment by imsyy** [comment]
已下线该接口
