### ISSUE TITLE
bilibili 接口出错

### ISSUE THREAD

**Issue by wzqww23** [imsyy/DailyHotApi#48]
### 问题描述

尝试访问b站接口时报错

`get xxx/bilibili`

显示错误；

`Cannot read properties of undefined (reading 'list')`

### 补充信息

其他接口可以正常使用

**Comment by imsyy** [comment]
已修复

**Comment by lainbo** [comment]
再次出现了这个问题，麻烦大佬有时间看下，包括官方示例站点

**Comment by imsyy** [comment]
已尝试修复，目前新增一个备用 api @lainbo

**Comment by IshuaWang** [comment]
好像现在又有这个bug了，如何修复呢？
