### ISSUE TITLE
知乎日报无法加载，用的是自己搭建的api

### ISSUE THREAD

**Issue by shmilyabyy** [imsyy/DailyHotApi#52]
### 问题描述

![image](https://github.com/imsyy/DailyHotApi/assets/77541484/7d668b04-c688-4ad2-a1e8-f3f831508332)
api所在的服务器是腾讯香港轻量。用docker按照教程部署的。
docker日志里有这么一条报错。
error: 出现致命错误：Error: Hostname/IP does not match certificate's altnames: Host: news-at.zhihu.com. is not in the cert's altnames

**Comment by 80imike** [comment]
我的环境和你一样 也是这样

https://github.com/imsyy/DailyHot/issues/23

但官方的可以 不知道为什么？
