### ISSUE TITLE
v2ex 热榜现在不支持了吗 ？

### ISSUE THREAD

**Issue by 80imike** [imsyy/DailyHotApi#53]
### 问题描述

v2ex 热榜现在不支持了吗 ？ 

我看文档里有写，但实际使用中没有呢？

**Comment by imsyy** [comment]
支持的，需要服务器能够访问外网 
[src/routes/v2ex.ts](https://github.com/imsyy/DailyHotApi/blob/master/src/routes/v2ex.ts)
