### ISSUE TITLE
添加数据库缓存上次爬取的数据，防止由于爬取失败导致没有数据可以展示

### ISSUE THREAD

**Issue by willow-god** [imsyy/DailyHotApi#54]
### 问题描述

大佬你好！感谢你的项目！我最近遇到了B站上时不时的抓取不到，导致没有信息可以显示，请问可以设置一个数据库保存上次爬取的信息吗？因为我发现B站上的数据变动并不是很大，相比于直接显示爬取失败报错，稍微延迟一点并不会影响体验，但是我不太会改，如果大佬有解决方法并且有空闲时间可以麻烦实现一下，我只是稍微提点建议，感谢大佬的项目！

**Comment by imsyy** [comment]
目前是有缓存的，30 分钟，由于请求方法是公用的，且每个接口返回的字段都不固定，无法统一判断某个接口是否请求成功，目前已尝试采用另一个 api 接口用来备用，也不知道能用多久 😭，B站的风控真是越来越强了

**Comment by willow-god** [comment]
> 目前是有缓存的，30 分钟，由于请求方法是公用的，且每个接口返回的字段都不固定，无法统一判断某个接口是否请求成功，目前已尝试采用另一个 api 接口用来备用，也不知道能用多久 😭，B站的风控真是越来越强了

嘿嘿好的！谢谢老哥！确实B站经常爬不到，先就这样用着吧，大不了缓存时间拉长一点嘿嘿👻
