### ISSUE TITLE
docker  镜像的 Hostloc 和 吾爱破解 接口报错：权限不足

### ISSUE THREAD

**Issue by 80imike** [imsyy/DailyHotApi#58]
### 问题描述

docker  镜像跑 Hostloc 和 吾爱破解 访问报错，已经是用的最新镜像，报的是权限不足

<img width="1506" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/82a14997-adfe-45c3-9f90-f6da842fcea3">

<img width="791" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/b415157d-c4c7-44b9-839c-5b3bd54216d1">

### 补充信息

换成 root 用户可能是最直接的解决方法

<img width="548" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/29fe0ab2-7228-4d89-909c-6eb53eb3686e">

如果能用普通用户，解决权限问题就更好了

**Comment by imsyy** [comment]
感觉这个还不是最大的问题，现在的问题是使用了 chromium 后内存占用太大了，不知道有什么解决方案 😂

**Comment by 80imike** [comment]
> 感觉这个还不是最大的问题，现在的问题是使用了 chromium 后内存占用太大了，不知道有什么解决方案 😂

用 chromium 基本 1g 起步

下面是一些优化参考

在 Docker 容器中运行 Chromium 时，内存占用高的问题可能会影响系统性能。以下是一些可能的解决方案和优化建议：

### 1. 限制内存使用
可以在启动 Docker 容器时限制其内存使用。例如，使用 `--memory` 选项来限制容器的最大内存使用量：

```bash
docker run --memory=1g your-chromium-image
```

### 2. 使用无头模式
运行 Chromium 的无头模式可以减少内存和 CPU 的使用。无头模式是指在没有图形用户界面的情况下运行浏览器：

```bash
chromium-browser --headless --disable-gpu --remote-debugging-port=9222
```

### 3. 禁用不必要的功能
禁用一些不必要的功能和插件可以减少内存使用。例如：

```bash
chromium-browser --headless --disable-gpu --disable-software-rasterizer --no-sandbox --disable-dev-shm-usage
```

解释：
- `--disable-gpu`：禁用 GPU 硬件加速。
- `--disable-software-rasterizer`：禁用软件光栅化。
- `--no-sandbox`：禁用沙箱（注意：这可能会降低安全性）。
- `--disable-dev-shm-usage`：禁用 `/dev/shm` 使用。

### 4. 使用较小的共享内存
Docker 默认将 `/dev/shm` 设为 64MB，这对于 Chromium 可能不够。可以在启动容器时增加共享内存的大小：

```bash
docker run --shm-size=1g your-chromium-image
```

### 5. 定期重启浏览器
如果 Chromium 长时间运行导致内存泄漏或内存占用不断增加，可以考虑定期重启浏览器实例。

### 6. 监控和分析内存使用
使用工具监控 Chromium 的内存使用情况，找出内存泄漏或高内存使用的原因。可以使用浏览器内置的开发者工具或外部监控工具。

### 7. 使用轻量级的浏览器
如果 Chromium 的内存占用问题无法解决，考虑使用更轻量级的浏览器，如 Puppeteer 或其他基于 Chromium 的无头浏览器。

### 8. 优化代码
如果你在运行自动化测试或网页抓取，优化你的脚本和代码，确保没有不必要的资源占用。

通过以上方法，你可以有效地减少 Docker 容器中 Chromium 的内存占用，提高系统的整体性能。

**Comment by imsyy** [comment]
目前这两个站点用的 discuz 都限制了 js 抓取，只能用浏览器模拟，先下线这个两个接口吧，等日后找到好方法再说吧

**Comment by love9wind** [comment]
这个能不能不用接口，直接用rss实现
