### ISSUE TITLE
能新增个微信读书豆瓣电影抖音的接口吗

### ISSUE THREAD

**Issue by DiSnail** [imsyy/DailyHotApi#6]
感觉接口太少了，澎湃腾讯百度头条都是新闻资讯类的，不知道大佬有没有时间加几个其它类型的接口，像微信读书、豆瓣电影、抖音、还有360的历史上的今天：https://hao.360.com/histoday/

**Comment by imsyy** [comment]
后续会考虑添加接口的

**Comment by opai8** [comment]
新人提问，在routers文件夹下添加接口，结果是'Not Found'，没有其他提示信息了，console.log咋不起作用

**Comment by imsyy** [comment]
> 新人提问，在routers文件夹下添加了一个自己写的接口(可能写的有问题)，结果是'Not Found'，没有其他提示信息了，是还要其他操作吗， 搞不懂错误在哪，console.log要怎么调试出来啊

console.log会在终端中输出，关于这个问题你检查下文件名或者有 fork 后的仓库吗
