### ISSUE TITLE
访问 hellogithub 接口出错, 使用最新 2.0 正式版

### ISSUE THREAD

**Issue by 80imike** [imsyy/DailyHotApi#60]
### 问题描述

<img width="1151" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/bfdf4552-8dac-422c-bb37-eb43dfefb1f5">

<img width="919" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/09efcbfd-ed9d-4a01-a5d2-038e61376c42">

**Comment by imsyy** [comment]
官方字段变化，已修复

**Comment by 80imike** [comment]
> 官方字段变化，已修复

@imsyy  是还没有发布吗？ 我看 docker 镜像 没有更新

**Comment by imsyy** [comment]
> > 官方字段变化，已修复
> 
> @imsyy 是还没有发布吗？ 我看 docker 镜像 没有更新

更新了
