### ISSUE TITLE
大佬，能自定义添加rss吗？

### ISSUE THREAD

**Issue by xiafei114** [imsyy/DailyHotApi#61]
### 问题描述

大佬，能自定义添加rss吗？

**Comment by imsyy** [comment]
是指的现有一个 RSS 链接，然后添加为接口吗

**Comment by xiafei114** [comment]
是的，可以允许自定义名称和rss链接

**Comment by imsyy** [comment]
有需要可以提交 pr 或者发 [issues](https://github.com/imsyy/DailyHotApi/issues/new?assignees=&labels=add&projects=&template=add.yml&title=%E6%B7%BB%E5%8A%A0%E6%8E%A5%E5%8F%A3)

**Comment by imsyy** [comment]
本项目目前没有类似于管理后台来实现自定义添加等功能
