### ISSUE TITLE
访问 地震速报 接口出错 

### ISSUE THREAD

**Issue by 80imike** [imsyy/DailyHotApi#64]
### 问题描述

get  /earthquake

<img width="1194" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/1e7b47b5-614a-4b34-880c-42010294b0c1">

<img width="1350" alt="image" src="https://github.com/imsyy/DailyHotApi/assets/1665201/cd1ed7f7-c406-4ab3-a095-c512bec6e08a">

**Comment by imsyy** [comment]
http://www.ceic.ac.cn/ajax/speedsearch
![image](https://github.com/imsyy/DailyHotApi/assets/42232682/986940f5-5762-4030-adbb-9c79218541b3)
应该是官方那边的问题
