### ISSUE TITLE
老板把网易也加上吧

### ISSUE THREAD

**Issue by JeazW** [imsyy/DailyHotApi#7]
老板把网易也加上吧

**Comment by imsyy** [comment]
网易新闻嘛

**Comment by MCBBC** [comment]
@imsyy 有空看一下tg消息

**Comment by imsyy** [comment]
> @imsyy 有空看一下tg消息

@MCBBC 哪一个是你呀 😂 有啥问题搁 GitHub 说吧

**Comment by MCBBC** [comment]
> > @imsyy 有空看一下tg消息
> 
> @MCBBC 哪一个是你呀 😂 有啥问题搁 GitHub 说吧

我是一只喵呜酱，给你发了几个文件
