### ISSUE TITLE
构建时还是存在错误

### ISSUE THREAD

**Issue by Adoubf** [imsyy/DailyHotApi#78]
### 代码报错如下：
src/routes/history.ts:47:38 - error TS2873: This kind of expression is always falsy.

47       cover: v.cover ? v.pic_share : null || null,
                                        ~~~~


Found 1 error in src/routes/history.ts:47

### 如图所示
![image](https://github.com/user-attachments/assets/29bb6aa5-d6f4-494a-8906-198ca2d7d9ad)

### 补充信息

_No response_

**Comment by Adoubf** [comment]
### 表达式
`cover: v.cover ? v.pic_share : null || null,`
使用是多余的，因为如果|| null表达式为假，则其计算结果已经为真。
### 修复
删除多余的|| null，将该行简化为
`cover: v.cover ? v.pic_share : null`

**Comment by Adoubf** [comment]
### 存在其他问题
npm run start

> dailyhot-api@2.0.4 start
> tsx src/index.ts

出现无法启动

**Comment by imsyy** [comment]
拉取下更新

**Comment by Adoubf** [comment]
十分感谢，已经解决
